services:
  mysql-bitelog:
    image: mysql:latest
    container_name: mysql-bitelog
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=bitelog
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - bitelog_db_data:/var/lib/mysql
      - ./bitelog-backend/src/main/resources/db/bitelog.sql:/docker-entrypoint-initdb.d/init.sql

  nginx-bitelog:
    image: nginx:1.18
    container_name: nginx-bitelog
    ports:
      - "8888:80"
    volumes:
      - ./bitelog-frontend-nginx-1.18.0/html/hmdp:/usr/share/nginx/html
      - ./bitelog-frontend-nginx-1.18.0/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./bitelog-frontend-nginx-1.18.0/conf/mime.types:/etc/nginx/mime.types
      - ./bitelog-frontend-nginx-1.18.0/logs:/var/log/nginx
    restart: always

  redis-bitelog:
    image: redis:latest
    container_name: redis-bitelog
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - bitelog_redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes


volumes:
  bitelog_db_data:
  bitelog_redis_data: