server:
  port: 8081
  servlet:
    encoding:
      force: true
      enabled: true
      charset: utf-8
spring:
  profiles:
    include: secret
  application:
    name: bitelog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bitelog?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
mybatis-plus:
  type-aliases-package: me.forty2.entity # 别名扫描包
logging:
  level:
    me.forty2: debug